### ISSUE TITLE
about your code

### ISSUE THREAD

**Issue by quhongcheng** [ricsinaruto/NeuralChatbots-DataFiltering#5]
I have a question about your code, 
Can your code effectively filter multiple turn dialog?
thanks

**Comment by ricsinaruto** [comment]
The code was written for single-turn filtering (source-target pairs), and all experiments in the paper are single-turn. However, it would be interesting to explore filtering for multi-turn dialog, but I think the code would have to be modified a bit.

Naively you could provide a source and target file, where each source line contains multiple utterances, but I don't know how well that would work.

**Comment by quhongcheng** [comment]
thanks
