### ISSUE TITLE
Unable to achieve published result in DailyDialogue

### ISSUE THREAD

**Issue by Bortrex** [ricsinaruto/NeuralChatbots-DataFiltering#6]
I had some troubles trying to replicate your results. Then I found this [#2341](https://github.com/nltk/nltk/issues/2341). 
Any chances to release your trained model?

**Comment by ricsinaruto** [comment]
Yes, it seems like the bleu scores in the paper were calculated with a wrong equation. Other metrics should be fine though.

All trained models from the paper are here: https://mega.nz/#!mI0iDCTI!qhKoBiQRY3rLg3K6nxAmd4ZMNEX4utFRvSby_0q2dwU
